### ISSUE TITLE
Output through GPIO

### ISSUE THREAD

**Issue by viniciuspereiras** [LTVA1/wav_player#1]
Hello! Nice job! Do you know if its possible to change the audio output through GPIO pins in place of speaker...?

**Comment by LTVA1** [comment]
https://github.com/LTVA1/wav_player/blob/main/wav_player_hal.c#L52

Signal is duplicated at PA6 pin.

**Comment by LTVA1** [comment]
I talked with the flipper developers, and looks like that PA6 (labeled as "A6" or "3" on GPIO pins edge) would be like standard pin for external audio. To have a good sound from it, attach it through ~400 kOhm resistance to one of the audio jack channel contacts amd connect GND pin to jack ground (see jack pinout if confused). The sound would be a little bit quiet but overall good. I suggest to not connect flipper to pc or charger if you want good signal (connecting it to somewhere through usb cable adds audible noise).

**Comment by viniciuspereiras** [comment]
Thank you!! :D
